# Makefile for the 2nd Project of ASA (LEIC-A @ IST 21/22)
# João Nuno Cardoso (99251) // José João Ferreira (99259)

CC = g++
CPPFLAGS = -g -std=c++11 -O3 -Wall -lm
TARGET_EXECS := p2 randGeneoTree

all: $(TARGET_EXECS)

p2: p2.cpp
randGeneoTree: randGeneoTree.cpp

clean:
	rm -f $(TARGET_EXECS)